name: Cache Demo

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache dependencies
        id: cache   # 👈 add id here
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-68e45b9

      - name: prime-cache-68e45b9
        run: echo "Cache result: ${{ steps.cache.outputs.cache-hit }}"
